mnp:
  jwt:
    secret: JUWbceHsFPBKZnXx+vs8tNnmISB823RTXSaRe/ubpAlRUrpuDbyDckydOYMkeyN4uB1trCY2HOmGiQBQhcKL8Q==
    accessTokenExpiration: 3600 # 1 hour
    refreshTokenExpiration: 604800 # 7 days

spring:
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
